export const HlsConfig = {
    autoStartLoad: true,
    initialLiveManifestSize: 1,
    maxBufferLength: 60,
    maxMaxBufferLength: 600,
    maxBufferSize: 60 * 1000 * 1000 * 2,
    nudgeOffset: 0.1,
    liveSyncDurationCount: 3,
    enableWorker: true,
    manifestLoadingTimeOut: 10000,
    manifestLoadingMaxRetry: 1,
    manifestLoadingRetryDelay: 500,
    manifestLoadingMaxRetryTimeout: 64000,
    levelLoadingMaxRetry: 4,
    levelLoadingRetryDelay: 500,
    levelLoadingMaxRetryTimeout: 64000,
    fragLoadingTimeOut: 20000,
    fragLoadingMaxRetry: 6,
    fragLoadingRetryDelay: 500,
    fragLoadingMaxRetryTimeout: 64000,
    startFragPrefetch: true,
    appendErrorMaxRetry: 3,
    abrEwmaFastLive: 5.0,
    abrEwmaSlowLive: 9.0,
    abrEwmaDefaultEstimate: 500000,
    abrBandWidthFactor: 0.95,
    abrBandWidthUpFactor: 0.7,
    minAutoBitrate: 0,
    maxBufferHole: 0, // Example: Allow a maximum buffer hole of 0.5 seconds
    maxStarvationDelay: 0, // Example: Maximum delay for quality switching in seconds
    capLevelToPlayerSize: true, //Limit quality level based on player size (365)
    lowLatencyMode: true,
    backBufferLength: 90,
    maxFragLookUpTolerance: 0,
};